server:
 error:
  include-message: always
  include-binding-errors: always

spring:
 datasource:
  password: 
  url: jdbc:postgresql://localhost:5432/registration
  username: 
 jpa:
  hibernate:
   ddl-auto: create-drop #Elimina toda la información cada vez que se crea la base de datos
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    format_sql: true
  show-sql: true
